// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projeto_mvc.Data;

#nullable disable

namespace projeto_mvc.Migrations
{
    [DbContext(typeof(ProjetoContext))]
    [Migration("20231012173030_industria-jogos")]
    partial class industriajogos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JogoPlataforma", b =>
                {
                    b.Property<int>("jogosId")
                        .HasColumnType("int");

                    b.Property<int>("plataformasId")
                        .HasColumnType("int");

                    b.HasKey("jogosId", "plataformasId");

                    b.HasIndex("plataformasId");

                    b.ToTable("JogoPlataforma");
                });

            modelBuilder.Entity("projeto_mvc.Models.Desenvolvedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LogoImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Desenvolvedores");
                });

            modelBuilder.Entity("projeto_mvc.Models.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CapaImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Dev")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Dev");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("projeto_mvc.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("projeto_mvc.Models.Plataforma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogoImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plataformas");
                });

            modelBuilder.Entity("projeto_mvc.Models.Plataforma_Jogo", b =>
                {
                    b.Property<int>("IdJogo")
                        .HasColumnType("int");

                    b.Property<int>("IdPlataforma")
                        .HasColumnType("int");

                    b.Property<int>("jogoId")
                        .HasColumnType("int");

                    b.Property<int>("plataformaId")
                        .HasColumnType("int");

                    b.HasKey("IdJogo", "IdPlataforma");

                    b.HasIndex("jogoId");

                    b.HasIndex("plataformaId");

                    b.ToTable("PlataformaJogos");
                });

            modelBuilder.Entity("JogoPlataforma", b =>
                {
                    b.HasOne("projeto_mvc.Models.Jogo", null)
                        .WithMany()
                        .HasForeignKey("jogosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projeto_mvc.Models.Plataforma", null)
                        .WithMany()
                        .HasForeignKey("plataformasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("projeto_mvc.Models.Jogo", b =>
                {
                    b.HasOne("projeto_mvc.Models.Desenvolvedor", "desenvolvedor")
                        .WithMany("jogos")
                        .HasForeignKey("Id_Dev")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("desenvolvedor");
                });

            modelBuilder.Entity("projeto_mvc.Models.Plataforma_Jogo", b =>
                {
                    b.HasOne("projeto_mvc.Models.Jogo", "jogo")
                        .WithMany("plataforma_jogos")
                        .HasForeignKey("jogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projeto_mvc.Models.Plataforma", "plataforma")
                        .WithMany("plataforma_jogos")
                        .HasForeignKey("plataformaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("jogo");

                    b.Navigation("plataforma");
                });

            modelBuilder.Entity("projeto_mvc.Models.Desenvolvedor", b =>
                {
                    b.Navigation("jogos");
                });

            modelBuilder.Entity("projeto_mvc.Models.Jogo", b =>
                {
                    b.Navigation("plataforma_jogos");
                });

            modelBuilder.Entity("projeto_mvc.Models.Plataforma", b =>
                {
                    b.Navigation("plataforma_jogos");
                });
#pragma warning restore 612, 618
        }
    }
}
